name: docker_build

on:
  workflow_dispatch: # Срабатывает при запуске вручную из интерфейса GitHub Actions
# on:
#   push:
#     branches:
#       - main # Срабатывает при коммите в ветку main

env:
  SOURCE     : "./"
  TARGET     : "~/docker_bind9"
  DOCKER_TAG : "${{ secrets.DOCKERHUB_USERNAME }}/certificate_authority:latest"

jobs:

  build_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: DOCKER/
          file: DOCKER/Dockerfile
          push: true
          tags: ${{ env.DOCKER_TAG }}
  
      - name: -------FINISH-Docker-Build-&-Push----------
        run: |
          echo "🍏 This job's status is ${{ job.status }}."

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: arturakh/bind9